### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Yakabuff** [Yakabuff/redarc#17]
- [x] fix indexer/optimize index strategy 
- [x] replace elasticsearch with postgres fts
- [x] change date to unix timestamps + refactor app
- [x] rename folders: ingest, frontend, api
- [x] refactor api. replace express api with python
- [x] subreddit watcher
- [x] image downloader queue
- [x] image api/view image on frontend
- [x] turn each worker into separate docker container
- [x] image_downloader container
- [x] subreddit_worker container
- [x] reddit_worker container
- [x] index_worker container
- [x] redis container
- [x] rotating logs
- [x] permalinks
- [x] image file name
- [x] image backfill script
- [ ] thread backfill script
- [x] tweak dockerignores
- [ ] pin deps
- [x] add subreddits to archive via web ui
- [x] unlist subreddits via web ui
- [ ] add postgres `POSTGRES_PASSWORD` envar to .env file
